import { Category, Transaction, Budget } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'salary',
    name: 'Salary',
    iconName: 'Briefcase',
    colorClass: 'bg-emerald-50',
    textClass: 'text-emerald-600',
    borderClass: 'border-emerald-100',
    type: 'income',
  },
  {
    id: 'freelancing',
    name: 'Freelancing',
    iconName: 'Laptop',
    colorClass: 'bg-blue-50',
    textClass: 'text-blue-600',
    borderClass: 'border-blue-100',
    type: 'income',
  },
  {
    id: 'business',
    name: 'Business',
    iconName: 'Building',
    colorClass: 'bg-indigo-50',
    textClass: 'text-indigo-600',
    borderClass: 'border-indigo-100',
    type: 'income',
  },
  {
    id: 'investment',
    name: 'Investment',
    iconName: 'TrendingUp',
    colorClass: 'bg-violet-50',
    textClass: 'text-violet-600',
    borderClass: 'border-violet-100',
    type: 'income',
  },
  {
    id: 'bonus',
    name: 'Bonus',
    iconName: 'Gift',
    colorClass: 'bg-pink-50',
    textClass: 'text-pink-600',
    borderClass: 'border-pink-100',
    type: 'income',
  },
  {
    id: 'other-income',
    name: 'Other',
    iconName: 'Coins',
    colorClass: 'bg-slate-50',
    textClass: 'text-slate-600',
    borderClass: 'border-slate-100',
    type: 'income',
  },
  {
    id: 'food',
    name: 'Food',
    iconName: 'Utensils',
    colorClass: 'bg-orange-50',
    textClass: 'text-orange-600',
    borderClass: 'border-orange-100',
    type: 'expense',
  },
  {
    id: 'shopping',
    name: 'Shopping',
    iconName: 'ShoppingBag',
    colorClass: 'bg-amber-50',
    textClass: 'text-amber-600',
    borderClass: 'border-amber-100',
    type: 'expense',
  },
  {
    id: 'transport',
    name: 'Transport',
    iconName: 'Car',
    colorClass: 'bg-sky-50',
    textClass: 'text-sky-600',
    borderClass: 'border-sky-100',
    type: 'expense',
  },
  {
    id: 'fuel',
    name: 'Fuel',
    iconName: 'Flame',
    colorClass: 'bg-yellow-50',
    textClass: 'text-yellow-600',
    borderClass: 'border-yellow-100',
    type: 'expense',
  },
  {
    id: 'grocery',
    name: 'Grocery',
    iconName: 'ShoppingCart',
    colorClass: 'bg-lime-50',
    textClass: 'text-lime-600',
    borderClass: 'border-lime-100',
    type: 'expense',
  },
  {
    id: 'rent',
    name: 'Rent',
    iconName: 'Home',
    colorClass: 'bg-purple-50',
    textClass: 'text-purple-600',
    borderClass: 'border-purple-100',
    type: 'expense',
  },
  {
    id: 'electricity',
    name: 'Electricity',
    iconName: 'Zap',
    colorClass: 'bg-yellow-50',
    textClass: 'text-yellow-600',
    borderClass: 'border-yellow-100',
    type: 'expense',
  },
  {
    id: 'internet',
    name: 'Internet',
    iconName: 'Globe',
    colorClass: 'bg-blue-50',
    textClass: 'text-blue-600',
    borderClass: 'border-blue-100',
    type: 'expense',
  },
  {
    id: 'mobile-recharge',
    name: 'Mobile Recharge',
    iconName: 'Smartphone',
    colorClass: 'bg-teal-50',
    textClass: 'text-teal-600',
    borderClass: 'border-teal-100',
    type: 'expense',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    iconName: 'Tv',
    colorClass: 'bg-pink-50',
    textClass: 'text-pink-600',
    borderClass: 'border-pink-100',
    type: 'expense',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    iconName: 'Heart',
    colorClass: 'bg-rose-50',
    textClass: 'text-rose-600',
    borderClass: 'border-rose-100',
    type: 'expense',
  },
  {
    id: 'education',
    name: 'Education',
    iconName: 'GraduationCap',
    colorClass: 'bg-indigo-50',
    textClass: 'text-indigo-600',
    borderClass: 'border-indigo-100',
    type: 'expense',
  },
  {
    id: 'travel',
    name: 'Travel',
    iconName: 'Plane',
    colorClass: 'bg-cyan-50',
    textClass: 'text-cyan-600',
    borderClass: 'border-cyan-100',
    type: 'expense',
  },
  {
    id: 'emi',
    name: 'EMI',
    iconName: 'CreditCard',
    colorClass: 'bg-red-50',
    textClass: 'text-red-600',
    borderClass: 'border-red-100',
    type: 'expense',
  },
];

// Stable mock date offsets
const getDateOffset = (daysAgo: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: 'demo-1',
    type: 'income',
    amount: 5800.00,
    category: 'salary',
    description: 'Monthly salary',
    date: getDateOffset(2),
    createdAt: new Date(getDateOffset(2)).toISOString(),
  },
  {
    id: 'demo-2',
    type: 'expense',
    amount: 1650.00,
    category: 'rent',
    description: 'Apartment rent',
    date: getDateOffset(4),
    createdAt: new Date(getDateOffset(4)).toISOString(),
  },
  {
    id: 'demo-3',
    type: 'expense',
    amount: 142.50,
    category: 'grocery',
    description: 'Grocery run',
    date: getDateOffset(6),
    createdAt: new Date(getDateOffset(6)).toISOString(),
  },
  {
    id: 'demo-4',
    type: 'income',
    amount: 900.00,
    category: 'freelancing',
    description: 'Client project',
    date: getDateOffset(10),
    createdAt: new Date(getDateOffset(10)).toISOString(),
  },
];

export const DEFAULT_BUDGETS: Budget[] = [
  {
    id: 'b-1',
    name: 'Food Budget',
    amount: 650.00,
    category: 'food',
    month: new Date().toISOString().substring(0, 7), // YYYY-MM
  },
  {
    id: 'b-2',
    name: 'Rent Budget',
    amount: 1800.00,
    category: 'rent',
    month: new Date().toISOString().substring(0, 7),
  },
  {
    id: 'b-3',
    name: 'Shopping Budget',
    amount: 450.00,
    category: 'shopping',
    month: new Date().toISOString().substring(0, 7),
  },
];
